### ISSUE TITLE
Manipulate files on the FTP Server

### ISSUE THREAD

**Issue by krlozadan** [xfally/cordova-plugin-ftp#16]
It would be a very nice feature if you could things like on the server side like:
- Rename files
- Move files around
Please tell me if I can be of any use :)

**Comment by flokixdev** [comment]
@krlozadan Useful features. Are you able to send a pull request?

**Comment by xfally** [comment]
As said in PR #14 

New features? I'm sorry no plan for that. Why? Because the existing cmd `ls` can finish most features (`exists, isFile, isDir, getSize`) you want. Need `pwd, rename`? Maybe we can check (or modify) GoldRaccoon and ftp4j to support them, but not all ftp server support those features, so they are unconsidered in this ftp client. The remaining `chmod, getPermissions` seem not be defined in [rfc959](https://www.w3.org/Protocols/rfc959/) although some PC ftp tools have implemented them.

If you think the feature is necessary, please try to implement it by yourself and share the PR. I can give your some suggestion maybe.
