### ISSUE TITLE
issue while Downloading PDF and store it

### ISSUE THREAD

**Issue by Srinivas-newAge** [xfally/cordova-plugin-ftp#38]
<img width="1001" alt="Screenshot 2022-02-11 at 7 46 35 PM" src="https://user-images.githubusercontent.com/97866617/153608661-43d015ad-c837-4fda-b69e-ac0e884070a5.png">
<img width="875" alt="Screenshot 2022-02-11 at 7 54 30 PM" src="https://user-images.githubusercontent.com/97866617/153608805-9b62a7f1-b19d-4613-b41c-071a92196c91.png">
<img width="863" alt="Screenshot 2022-02-11 at 7 58 36 PM" src="https://user-images.githubusercontent.com/97866617/153609683-79f4e1a7-9b86-4d16-b028-99643b42cb33.png">

**cannot able to download pdf from the server and how to store it in a particular directory, where to mention the directory, is there is any method? 

Xcode:12.5
ionic version:5.4.16
device:iphone 12mini (simulator) ios 14.5

And also provide share access in info list**

**Comment by xfally** [comment]
Of course it will go wrong, because you are trying to access the application directory which is Read-only on iOS. Refer to [test example](https://github.com/xfally/cordova-plugin-ftp/blob/master/test/www/js/index.js) and [Cordova FileSystem API](https://cordova.apache.org/docs/en/10.x/reference/cordova-plugin-file/index.html), then you can choose the right directory to store your files.

**Comment by Srinivas-newAge** [comment]
thanks
